name: CDPS-server

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: cdps:latest
          outputs: type=docker,dest=/tmp/CDPS.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CDPS
          path: /tmp/CDPS.tar.gz

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: CDPS
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/CDPS.tar.gz
          docker image ls -a